project_name: kr8
builds:
  -
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    main: .
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: kr8
archive:
  format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
nfpm:
  vendor: Apptio TechOps
  homepage: "https://github.com/apptio/kr8"
  maintainer: Lee Briggs <lbriggs@apptio.com>
  description: "Opinionated configuration management tool for Kubernetes Cluster"
  license: MIT
  formats:
    - rpm
    - deb
  bindir: /usr/local/bin
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
dist: dist
dockers:
  -
    image: apptio/kr8
    dockerfile: Dockerfile-goreleaser
    tag_templates:
    - "{{ .Tag }}"
    - latest
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
brew:
  github:
    owner: apptio
    name: homebrew-tap

  commit_author:
    name: release
    email: release@apptio.com

  homepage: "https://github.com/apptio/kr8"
  description: "Opinionated configuration management tool for Kubernetes Cluster"
