language: go
addons:
  apt:
    packages:
    - rpm
services:
- docker
after_success:
- test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_install:
  - curl https://glide.sh/get | sh
  - glide i

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
env:
  global:
  - secure: bI9L8fKhLgq+KqzC7HICelO/blH3XuZzQIo7wUdSz+fYjvpS+4VEZR6HaNLdmZ3eXoN9W2ju9SFeCGhylmj0BQDn9AbTz0oe0DRLPKDb/zWy7zRxmKcTBBQ25Ko3SfRLHnhwEwi36RbrKMTfTycnD6IdtFAiAxW1JGOPrn6LQ+FOCLi0rcSaVpUSjwHhfCD6e5Q2vNjAVKxz6oeHo7Wd2vgglCpMoaJrSGAPEj88OZyyfbwwuDAHp2GcZQKF0Fv689bf97uchAmcAKThS4V600sQLLK0Z0INSwN6zLfJei1bqp4kb9aLse2pW5+V1vsZiUhbPF2bN8B3p7udfKX8AS1BRgvflj+ttW8NHRnObNm9NaUM6vqeLPjmAxl2c5GsfBU67yiBf4+nqtT/f6JNoZeY3VMCj/Wvvvl/RFPM+EREX9UyXQ1vv/sxHXZkVta0rYtdYx1kLmIGxlY9jYLleYHFEHYlTylllH3YUUiyyU6iqzxAJyw1en0gc6DrJAZvN0d5QiHd54wESn0Ta7et0oYpLbCL3o2ZXjHa5R7deNbO+AVi9iM3i5Dm+PeQAQpgoDvj7JCO4seVCuamh55yNe3XXC9ZD6wn/kX7jaqFO0/H1pvPdQcOO2lE7k7sGquvfF3JhpCWE1hdgrJA1YhZBYIZn65c3Pcffvv/9G6VSbU=
  - secure: Wzdf0Shm6P5Z705oNZ+oPVtJ46zDawsadLuyC1FMTF5BxFpiGze52PXR4/M2ZlScIkk3/F3vF4kKqlIzkm6D0ShPyf/6/KA1c50PhHvWG9g8wUGcdVVEg5bu5bgR06STz5kuOuCYhAI1bm8ezaJT5uKRxgeOzcWsYjw4InlnvdekWmPyBWEelar/J6PBnPKie4HELeIDix7tX9z2W0GltB133WqYuqfOQmXphbyMmjc8D7vv4xgrJif40t2vkOFZe1lxadeexIg+zauHY6rnZMLjx4q8FC15sItwScZvFJReHqvtuUlAhf8fLdW31vn9GcNV3PRuQgDzPSIy1gPLlASRaOfNoy9zNfYDSomNwNj+6erzsSRZrytXBvsjaJHGtuyFRShKQdZMjhQoSWsWABHUQuExLOOYOFxI9wg9T0/4s9Md1t856Ns4/wcV63KgfiIW2RDKRslnJMIy/OvkukoTkM3vif22q+HJ6wz8rVXEquBWp8zmEvDV+iHN4YGDVD66x1bVbg5T9t3mp+sQ+4KGNaUiqx1CcMgBEartXjfZKnjpcfQH8nGCazSffV4GEYPpo3JeXqIZRlMuEQGqdZR4fsaQHe69z/oNJkU3ii8UJ5blKwONfw0AJt7/5c1GQltV5h7KW6+RJww9cKvM3L31eZgZS2FCot0xC32l7k4=
  matrix:
    secure: XpvckkNYT7jZfjQrJNuWTh2bpG8OptjWyX9ONdY+4awu7yj8g9HyxR/+HYfc6Rjfy2REhhavIMrLJ0FCNqZd7myiqiPKv3J8m9MjSnHJEjlvI2KBhGZwT34xzOxzb+i4xdh/oM0ZBJJyMJjuaz4STJEVYGf4Uix2f2oEQlbxkh4O5qPzeSjOP21RV1PwtKl0EUX6IqLTYWBN8kRMiZXpxBq4i2c+DLR+2qSa7gnH4wPYBS5GCf/gGO4BU8vPIzffYvQVnG1kvcw6rUoKJ+66t2mLjTi8dWc0NEG+uFBo4/jvDLKKohPGxU/snW5sR6UaTK3c0pbuOHXI+EZ0UexcLb4Mib74TMMscbCcgOnsUxd8lMs8PR3NLfTWx0MwVELTDerejd1WHZFpwv7rUavb2lX17wBKVemQ73F1rVwqDWhQujjaThHECh8yJrW6rW0xwws1kU7tFjb6VFBjpeaefifNKyavbvIBr4lYBgHfidb6SCK+yPSEbPN1yJyHrmMlNIUtutn9G/uSdWZ1Pv9aQviAXdxZDgdhbbvfH48Z1Qxxjs2vJScWz/tEdVfaHyNy8k4bNslBnpEtwKNAhXZfrIvF2fpK55qDQfEz7475c9IoG4sImXbvFHOEIt/xq+bqTDWWYwO502xPWJ9k49xgfEnzEFqhNGEVQUZ1U560/60=
