version: '2'



tasks:
  mkdocs:
    desc: Install mkdocs
    cmds:
      - pipenv install mkdocs
      - pipenv install mkdocs-material
  web-local:
    desc: Run the site locally
    cmds:
      - pipenv run mkdocs serve
  web-deploy:
    desc: Build website assets
    cmds:
      - pipenv run mkdocs build
      - pipenv run mkdocs gh-deploy

